version: '3.8'

services:
  api:
    image: hqkietsoft/english-syntax-parser:latest
    container_name: english_parser_app
    # ports:
    #   # Map port 5000 của Host vào port 8000 của Container
    #   # Vì Nginx của bạn đang proxy_pass http://localhost:5000
    #   - "5000:5000" 
    expose:
      - "5000"
    environment:
      - LOG_LEVEL=INFO
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - app_network

  # =========================================
  # 2. NGINX REVERSE PROXY (Mới thêm)
  # =========================================
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx 
    depends_on:
      - api
    networks:
      - app_network


  # =========================================
  # MONITORING STACK
  # =========================================
  loki:
    image: grafana/loki:2.9.0
    container_name: monitoring_loki
    volumes:
      - ./monitoring/loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app_network

  promtail:
    image: grafana/promtail:3.0.0
    container_name: monitoring_promtail
    privileged: true
    user: root
    ports:
      - "9080:9080"
    volumes:
      - ./monitoring/promtail/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/nginx:/var/log/nginx:ro
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
      - nginx
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - app_network



  # Metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app_networks

  node_exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    ports:
      - "9100:9100"
    networks:
      - app_networks

networks:
  app_network:
    driver: bridge

# volumes:
#   nginx_logs:
