name: Build and Push Docker Image

on:
  push:
    branches: ["master"]

jobs:
  # Job 1: Build Docker Image
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hqkietsoft/english-syntax-parser:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # --------------------------------------------------------
      # 1. SERVER CŨ
      # --------------------------------------------------------
      - name: Deploy to Old Manual Server
        uses: appleboy/ssh-action@v1.0.0
        continue-on-error: true 
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p english-syntax-parser
            cd english-syntax-parser
            
            if [ -d ".git" ]; then
              git pull origin master
            else
              git clone https://github.com/hqkietsoft/english-syntax-parser.git .
            fi
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f

      # --------------------------------------------------------
      # 2. SERVER MỚI (Swarm Manager)
      # --------------------------------------------------------
      - name: Deploy to New Swarm Cluster
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_SWARM_MANAGER_IP }} 
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY_TF }}
          script: |
            mkdir -p english-syntax-parser
            cd english-syntax-parser
            
            if [ -d ".git" ]; then
              git pull origin master
            else
              git clone https://github.com/hqkietsoft/english-syntax-parser.git .
            fi
            
            mkdir -p model_weights

            docker pull hqkietsoft/english-syntax-parser:latest

            docker stack deploy -c docker-compose.yml app_stack --with-registry-auth
            
            docker service update --image hqkietsoft/english-syntax-parser:latest app_stack_api --force

            docker image prune -f
